Add episode for additional resources
HealthBioscienceIDEAS/microscopy-novice pull request #50
Opened 2024-02-23 13:53 UTC by K-Meech

Closes https://github.com/HealthBioscienceIDEAS/microscopy-novice/issues/29

This adds an episode linking to various online resources for image analysis and microscopy

2024-03-06 11:36 UTC, davecash75 requested changes
Looks great - Just a couple of point that could be expanded.

2024-03-06 11:36 UTC, davecash75 commented on episodes/additional-resources.md
> +- [image.sc forum](https://forum.image.sc/)
Maybe a brief sentence on what this covers - Fiji, Napari, other programs? so that people know when they should look at this.

2024-03-06 11:36 UTC, davecash75 commented on episodes/additional-resources.md
> +- [Pete Bankhead's bioimage book](https://bioimagebook.github.io/)
Again maybe a brief sentence about what this covers, good resource delving deeper in the principles discussed during this course.

2024-03-07 09:52 UTC, K-Meech commented
Thanks @davecash75 - I decided to add a short sentence describing all the links. Feel free to merge if you're happy with it!

2024-03-07 12:30 UTC, davecash75 approved these changes
Thanks, I think these extra bits really help!

2024-03-07 12:30 UTC, merged